name: HPET
version: '4.7.5'
main: it.heron.hpet.Pet
depend: [ProtocolLib]
api-version: 1.13
softdepend: [PlaceholderAPI, HeadDatabase, Vault, SuperVanish, PremiumVanish, CMI, MythicMobs, ItemsAdder, ModelEngine, HeadDB]
commands:
  hpet:
permissions:
  pet.version:
    default: true
  pet.command:
    default: true