name: HPET
version: '${version}'
main: it.heron.hpet.main.PetPlugin
depend: [packetevents]
api-version: 1.20
description: 'The packet based pet plugin'
softdepend: [PlaceholderAPI, HeadDatabase, Vault, SuperVanish, PremiumVanish, CMI, MythicMobs, ItemsAdder, ModelEngine, HeadDB]
permissions:
  pet.version:
    default: true
  pet.command:
    default: true
libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.1.4