name: HPET
version: 3.7.1
main: it.heron.hpet.Pet
depend: [ProtocolLib]
api-version: 1.13
softdepend: [PlaceholderAPI, HeadDatabase, Vault, SuperVanish, PremiumVanish, CMI, MythicMobs]
commands:
  pet:
  hpet:
  pets:
permissions:
  pet.version:
    default: true
  pet.command:
    default: true