name: HPET
version: '${project.version}'
main: it.heron.hpet.Pet
depend: [ProtocolLib]
api-version: 1.13
softdepend: [PlaceholderAPI, HeadDatabase, Vault, SuperVanish, PremiumVanish, CMI, MythicMobs, ItemsAdder, ModelEngine]
commands:
  pet:
  hpet:
permissions:
  pet.version:
    default: true
  pet.command:
    default: true