name: HPET
version: '4.7-beta'
main: it.heron.hpet.main.PetPlugin
depend: [ProtocolLib]
api-version: 1.13
softdepend: [PlaceholderAPI, HeadDatabase, Vault, SuperVanish, PremiumVanish, CMI, MythicMobs, ItemsAdder, ModelEngine, HeadDB]
commands:
  hdev:
    description: "Get information and help about all HDEV products"
  hpet:
permissions:
  pet.version:
    default: true
  pet.command:
    default: true